import { defineType, defineField, defineArrayMember } from 'sanity';

export default defineType({
  name: 'headsUp',
  title: 'Heads Up Program',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'safeHaven', title: 'Safe Haven' },
    { name: 'support', title: 'Who We Support' },
    { name: 'experience', title: 'Retreat Experience' },
    { name: 'care', title: 'Evidence-Based Care' },
    { name: 'included', title: "What's Included" },
    { name: 'community', title: 'Community Powered' },
    { name: 'impact', title: 'Impact Stats' },
    { name: 'cta', title: 'Call to Action' },
  ],
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero Section',
      type: 'heroSection',
      description: 'The hero banner at the top of the Heads Up page.',
      group: 'hero',
    }),

    defineField({
      name: 'safeHavenHeading',
      title: 'Safe Haven Heading',
      type: 'string',
      description: 'Heading for the opening "Safe Haven for Healing" section.',
      initialValue: 'A Safe Haven for Healing',
      group: 'safeHaven',
    }),
    defineField({
      name: 'safeHavenBody',
      title: 'Safe Haven Body',
      type: 'portableText',
      description: 'Intro paragraphs about the retreat. Write as separate paragraphs — each renders with breathing space.',
      group: 'safeHaven',
    }),
    defineField({
      name: 'safeHavenImage',
      title: 'Safe Haven Image',
      type: 'image',
      description: 'Photo shown beside the opening text. Recommended: 600x400px, landscape.',
      options: { hotspot: true },
      group: 'safeHaven',
    }),

    defineField({
      name: 'supportHeading',
      title: 'Support Section Heading',
      type: 'string',
      description: 'Heading for the "Who We Support" section.',
      initialValue: 'Who We Support',
      group: 'support',
    }),
    defineField({
      name: 'supportSubtitle',
      title: 'Support Section Subtitle',
      type: 'text',
      rows: 2,
      description: 'Short line below the support heading.',
      group: 'support',
    }),
    defineField({
      name: 'supportCards',
      title: 'Who We Support Cards',
      type: 'array',
      description: 'Cards describing who the Heads Up program helps. Icons are picked from a fixed list.',
      of: [{ type: 'supportCard' }],
      group: 'support',
    }),

    defineField({
      name: 'experienceHeading',
      title: 'Experience Section Heading',
      type: 'string',
      description: 'Heading for the "Retreat Experience" journey section.',
      initialValue: 'The Retreat Experience',
      group: 'experience',
    }),
    defineField({
      name: 'experienceSubtitle',
      title: 'Experience Section Subtitle',
      type: 'text',
      rows: 2,
      description: 'Short line below the experience heading.',
      group: 'experience',
    }),
    defineField({
      name: 'experienceItems',
      title: 'Experience Steps',
      type: 'array',
      description: 'Phases of the retreat experience. Icons are picked from a fixed list.',
      of: [{ type: 'experienceItem' }],
      group: 'experience',
    }),

    defineField({
      name: 'careHeading',
      title: 'Care Section Heading',
      type: 'string',
      description: 'Heading for the Evidence-Based Care section.',
      initialValue: 'Evidence-Based Care',
      group: 'care',
    }),
    defineField({
      name: 'careImage',
      title: 'Care Section Image',
      type: 'image',
      description: 'Photo shown beside the pillars. Recommended: 600x400px, landscape.',
      options: { hotspot: true },
      group: 'care',
    }),
    defineField({
      name: 'carePillars',
      title: 'Evidence-Based Care Pillars',
      type: 'array',
      description: 'Pillars of evidence-based care used in the program. Icons are picked from a fixed list.',
      of: [{ type: 'carePillar' }],
      group: 'care',
    }),

    defineField({
      name: 'includedHeading',
      title: "What's Included Heading",
      type: 'string',
      description: "Heading for the What's Included grid.",
      initialValue: "What's Included",
      group: 'included',
    }),
    defineField({
      name: 'includedSubtitle',
      title: "What's Included Subtitle",
      type: 'text',
      rows: 2,
      description: 'Short line below the included heading.',
      group: 'included',
    }),
    defineField({
      name: 'includedItems',
      title: "What's Included Items",
      type: 'array',
      description: "Items in the What's Included grid. Icons are picked from a fixed list.",
      of: [{ type: 'includedItem' }],
      group: 'included',
    }),

    defineField({
      name: 'communityHeading',
      title: 'Community Section Heading',
      type: 'string',
      description: 'Heading for the "Powered by Community" section.',
      initialValue: 'Powered by Community',
      group: 'community',
    }),
    defineField({
      name: 'communityIntro',
      title: 'Community Intro Paragraph',
      type: 'text',
      rows: 3,
      description: 'Intro paragraph describing the role of volunteers.',
      group: 'community',
    }),
    defineField({
      name: 'communityBullets',
      title: 'Community Bullet Points',
      type: 'array',
      description: 'Short bullet points about how community support works — keep each under 80 chars for best visual fit.',
      of: [defineArrayMember({ type: 'string' })],
      group: 'community',
    }),
    defineField({
      name: 'communityButton',
      title: 'Community Section Button',
      type: 'object',
      description: 'Call-to-action button below the bullets.',
      group: 'community',
      fields: [
        defineField({ name: 'text', title: 'Button Text', type: 'string' }),
        defineField({
          name: 'href',
          title: 'Button Link',
          type: 'string',
          description: 'Where the button goes (e.g., "/get-involved/volunteer").',
        }),
      ],
    }),
    defineField({
      name: 'communityImage',
      title: 'Community Section Image',
      type: 'image',
      description: 'Photo shown beside the community section text. Recommended: 600x400px, landscape.',
      options: { hotspot: true },
      group: 'community',
    }),

    defineField({
      name: 'impactHeading',
      title: 'Impact Section Heading',
      type: 'string',
      description: 'Heading for the Impact Stats section.',
      initialValue: 'Our Growing Impact',
      group: 'impact',
    }),
    defineField({
      name: 'impactSubtitle',
      title: 'Impact Section Subtitle',
      type: 'text',
      rows: 2,
      description: 'Short line below the impact heading.',
      group: 'impact',
    }),
    defineField({
      name: 'impactStats',
      title: 'Impact Statistics',
      type: 'array',
      description: "Key numbers showing the program's impact. Value is the number, suffix is an optional trailing character (e.g., '+' or '%').",
      of: [{ type: 'statItem' }],
      validation: (rule) => rule.max(4).warning('4 stats maximum for this layout.'),
      group: 'impact',
    }),

    defineField({
      name: 'ctaHeading',
      title: 'CTA Heading',
      type: 'string',
      description: 'Heading of the closing call-to-action section.',
      initialValue: 'Creating Space for Healing',
      group: 'cta',
    }),
    defineField({
      name: 'ctaSubtitle',
      title: 'CTA Subtitle',
      type: 'text',
      rows: 3,
      description: 'Short paragraph under the CTA heading.',
      group: 'cta',
    }),
    defineField({
      name: 'ctaPrimaryButton',
      title: 'CTA Primary Button',
      type: 'object',
      description: 'Primary button at the bottom of the page.',
      group: 'cta',
      fields: [
        defineField({ name: 'text', title: 'Button Text', type: 'string' }),
        defineField({ name: 'href', title: 'Button Link', type: 'string' }),
      ],
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Heads Up Program' };
    },
  },
});
