import { defineType, defineField } from 'sanity';

export default defineType({
  name: 'volunteerPage',
  title: 'Volunteer Page',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'whyVolunteer', title: 'Why Volunteer' },
    { name: 'howToHelp', title: 'How You Can Help' },
    { name: 'impact', title: 'Volunteer Impact' },
    { name: 'testimonials', title: 'Testimonials' },
    { name: 'faq', title: 'FAQ' },
    { name: 'form', title: 'Application Form' },
    { name: 'cta', title: 'Call to Action' },
  ],
  fields: [
    defineField({
      name: 'hero',
      title: 'Hero Section',
      type: 'heroSection',
      description: 'The hero banner at the top of the Volunteer page.',
      group: 'hero',
    }),

    defineField({
      name: 'whyVolunteerHeading',
      title: 'Why Volunteer Heading',
      type: 'string',
      description: 'Heading for the first section explaining why someone might volunteer.',
      initialValue: 'Why Volunteer?',
      group: 'whyVolunteer',
    }),
    defineField({
      name: 'whyVolunteerBody',
      title: 'Why Volunteer Body',
      type: 'portableText',
      description: 'Content explaining why volunteering with Jewmanity is meaningful. Write as paragraphs.',
      group: 'whyVolunteer',
    }),
    defineField({
      name: 'whyVolunteerImage',
      title: 'Why Volunteer Image',
      type: 'image',
      description: 'A warm photo of volunteers in action. Recommended: 600x400px, landscape.',
      options: { hotspot: true },
      group: 'whyVolunteer',
    }),

    defineField({
      name: 'howToHelpHeading',
      title: 'How To Help Heading',
      type: 'string',
      description: 'Heading for the section that lists specific volunteer opportunities.',
      initialValue: 'How You Can Help',
      group: 'howToHelp',
    }),
    defineField({
      name: 'howToHelpSubtitle',
      title: 'How To Help Subtitle',
      type: 'text',
      rows: 2,
      description: 'Short intro describing the range of ways to help.',
      group: 'howToHelp',
    }),
    defineField({
      name: 'howToHelpCards',
      title: 'How To Help Cards',
      type: 'array',
      description: 'Cards describing different ways people can volunteer.',
      of: [{ type: 'howToHelpCard' }],
      group: 'howToHelp',
    }),

    defineField({
      name: 'impactHeading',
      title: 'Impact Section Heading',
      type: 'string',
      description: 'Heading for the stats section showing program scale.',
      initialValue: 'The Impact of Volunteering',
      group: 'impact',
    }),
    defineField({
      name: 'impactIntro',
      title: 'Impact Section Intro',
      type: 'text',
      rows: 3,
      description: 'Short paragraph introducing the impact stats.',
      group: 'impact',
    }),
    defineField({
      name: 'impactStats',
      title: 'Volunteer Impact Stats',
      type: 'array',
      description: 'Key numbers showing volunteer program impact. Value is the number, suffix is an optional trailing character (e.g., "+" or "%").',
      of: [{ type: 'statItem' }],
      validation: (rule) => rule.max(4).warning('4 stats maximum for this layout.'),
      group: 'impact',
    }),

    defineField({
      name: 'testimonialsHeading',
      title: 'Testimonials Heading',
      type: 'string',
      description: 'Heading above the testimonial carousel.',
      initialValue: 'What Our Volunteers Say',
      group: 'testimonials',
    }),
    defineField({
      name: 'testimonialsSubtitle',
      title: 'Testimonials Subtitle',
      type: 'text',
      rows: 2,
      description: 'Short intro for the testimonials section.',
      group: 'testimonials',
    }),

    defineField({
      name: 'faqHeading',
      title: 'FAQ Heading',
      type: 'string',
      description: "Heading for the FAQ section. Default is 'Frequently Asked Questions' — change if you prefer something like 'Common Questions' or 'Volunteer FAQs'.",
      initialValue: 'Frequently Asked Questions',
      group: 'faq',
    }),
    defineField({
      name: 'faqSubtitle',
      title: 'FAQ Subtitle',
      type: 'text',
      rows: 2,
      description: 'Short line under the FAQ heading.',
      group: 'faq',
    }),
    defineField({
      name: 'formHeading',
      title: 'Form Heading',
      type: 'string',
      description:
        'Heading above the volunteer application form. The form fields and submission behavior are managed via Formspree in code — contact your developer to change those.',
      initialValue: 'Volunteer Application',
      group: 'form',
    }),
    defineField({
      name: 'formSubtitle',
      title: 'Form Subtitle',
      type: 'text',
      rows: 2,
      description: 'Short intro text above the form.',
      group: 'form',
    }),
    defineField({
      name: 'formPrivacyNote',
      title: 'Form Privacy Note',
      type: 'text',
      rows: 2,
      description: 'Privacy/confidentiality note displayed near the form. Review wording with care — this sets user expectations about how their information is handled.',
      group: 'form',
    }),

    defineField({
      name: 'ctaHeading',
      title: 'CTA Heading',
      type: 'string',
      description: 'Heading for the bottom call-to-action section.',
      initialValue: 'Ready to Get Involved?',
      group: 'cta',
    }),
    defineField({
      name: 'ctaDescription',
      title: 'CTA Description',
      type: 'text',
      rows: 3,
      description: 'Encouraging text below the CTA heading.',
      group: 'cta',
    }),
    defineField({
      name: 'ctaPrimaryButton',
      title: 'CTA Primary Button',
      type: 'object',
      description: 'Main call-to-action button.',
      group: 'cta',
      fields: [
        defineField({ name: 'text', title: 'Button Text', type: 'string' }),
        defineField({
          name: 'href',
          title: 'Button Link',
          type: 'string',
          description:
            "Where the main CTA button links. Use '#volunteer-form' to scroll to the form on this page, or an external URL.",
        }),
      ],
    }),
    defineField({
      name: 'ctaSecondaryButton',
      title: 'CTA Secondary Button',
      type: 'object',
      description: 'Secondary outlined button displayed next to the primary button.',
      group: 'cta',
      fields: [
        defineField({ name: 'text', title: 'Button Text', type: 'string' }),
        defineField({ name: 'href', title: 'Button Link', type: 'string', description: 'Where the secondary CTA links.' }),
      ],
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Volunteer Page' };
    },
  },
});
